apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args: 
    - sleep
    - "1600"
    volumeMounts:
    - mountPath:  /giropops
      name: ubuntu-emptydir
    resources:
      limits:
        cpu: "1.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  - image: nginx
    name: webserver
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /giropops
      name: nginx-emptydir
    resources:
      limits:
        cpu: "1.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: nginx-emptydir
    emptyDir:
      sizeLimit: 256Mi
  - name: ubuntu-emptydir
    emptyDir:
      sizeLimit: 256Mi
