apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-girus
  name: nginx-girus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-girus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-girus
    spec:
      containers:
      - image: nginx:1.16.0
        name: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.7"
          requests: 
            memory: "64Mi"
            cpu: "0.5"
